version: '3.8'

services:
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    ports:
      - "389:389"
    environment:
      LDAP_ORGANISATION: "MyOrg"
      LDAP_DOMAIN: "myorg.com"
      LDAP_ADMIN_PASSWORD: admin
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
    restart: unless-stopped

  user-service:
    build:
      context: .
    container_name: user-service
    ports:
      - "8080:8080"
    depends_on:
      - openldap
    env_file:
      - .env
    restart: unless-stopped

volumes:
  openldap_data:
  openldap_config: