name: Deploy to AWS EC2

on:
  push:
    branches:
      - main    # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest    # Use the latest Ubuntu runner in GitHub Actions

    steps:
      # ----------------------------------------
      # 1. Checkout the repository
      # ----------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ----------------------------------------
      # 2. Set up Docker environment
      # ----------------------------------------
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # ----------------------------------------
      # 3. Build the Docker image
      # ----------------------------------------
      - name: Build Docker image
        run: docker build -t camping-service-repo .

      # ----------------------------------------
      # 4. Check AWS CLI version
      #    (needed for aws s3 cp commands)
      # ----------------------------------------

      - name: Check AWS CLI version
        run: aws --version

      # ----------------------------------------
      # 5. Configure AWS credentials for the runner
      #    (provides environment variables for AWS CLI)
      # ----------------------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1           # Change to your AWS region

      # ----------------------------------------
      # 6. Push the Docker image to Amazon ECR
      # ----------------------------------------
      - name: Push Docker image to ECR
        run: |
          aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 319805118398.dkr.ecr.ap-northeast-1.amazonaws.com
          docker tag camping-service-repo 319805118398.dkr.ecr.ap-northeast-1.amazonaws.com/camping-service-repo:latest
          docker push 319805118398.dkr.ecr.ap-northeast-1.amazonaws.com/camping-service-repo:latest

      # ----------------------------------------
      # 7. Create the private key file for SSH
      #    (the key should be stored in a GitHub secret)
      # ----------------------------------------
      - name: Create SSH key file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem    # Restrict permissions for security
      

      # ----------------------------------------
      # 8. SSH into the EC2 instance and deploy the Docker container:
      #    - Pull the Docker image from ECR
      #    - Stop any running container
      #    - Start the new container version
      # ----------------------------------------
      - name: Deploy Docker to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@13.231.23.72 '
            set -x
            docker pull 319805118398.dkr.ecr.ap-northeast-1.amazonaws.com/camping-service-repo:latest
            docker stop camping-service-repo || true
            docker rm camping-service-repo || true
            docker run -d --name camping-service-repo -p 8080:8080 319805118398.dkr.ecr.ap-northeast-1.amazonaws.com/camping-service-repo:latest
          '

      # ----------------------------------------
      # 9. Delete the SSH key file after deployment
      #    (important for security)
      # ----------------------------------------
      - name: Clean up SSH key
        run: rm -f key.pem